/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.map.clubedowhisky.view;

import static com.sun.corba.se.impl.util.Utility.printStackTrace;
import br.edu.map.clubedowhisky.controller.ControllerFornecedor;
import br.edu.map.clubedowhisky.controller.ControllerProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.edu.map.clubedowhisky.model.Fornecedor;
import br.edu.map.clubedowhisky.model.Produto;


public class TelaCadastroProduto extends javax.swing.JFrame {

    Produto modelProdutos = new Produto();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ArrayList<Produto> listamModelProdutos = new ArrayList<Produto>();
    ArrayList<Fornecedor> listaFornecedor = new ArrayList<Fornecedor>();
    String tipoCadastro;
    
    
    public TelaCadastroProduto() {
        initComponents();
        setLocationRelativeTo(null);
        this.carregarProdutos();
        this.listarFornecedor();
        this.desabilitarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        tfCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfValor = new javax.swing.JFormattedTextField();
        tfEstoque = new javax.swing.JFormattedTextField();
        jtfNome = new javax.swing.JTextField();
        cbFornecedores = new componentes.UJComboBox();
        tfCodigoBarras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setToolTipText("Cadastro de Produtos");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome Bebida:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 10, -1, -1));

        jLabel2.setText("Valor Garrafa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel3.setText("Fornecedor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, -1));

        jLabel4.setText("Quant. Estoque:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Add.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Modify.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/No.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        tbProdutos.setAutoCreateRowSorter(true);
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Valor Garrafa", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbProdutos);
        if (tbProdutos.getColumnModel().getColumnCount() > 0) {
            tbProdutos.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 580, 230));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Save.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        tfCodigo.setEditable(false);
        tfCodigo.setEnabled(false);
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 82, -1));

        jLabel5.setText("Código:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 31, 111, -1));
        jPanel1.add(tfEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 110, -1));
        jPanel1.add(jtfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 31, 259, -1));
        jPanel1.add(cbFornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 380, -1));

        tfCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodigoBarrasKeyReleased(evt);
            }
        });
        jPanel1.add(tfCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        jLabel6.setText("Código de barras:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novoProduto();
        habilitarCampos();
        tipoCadastro = "novo";
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
         TelaPesquisarProduto telaPesquisarProduto = new TelaPesquisarProduto();
        telaPesquisarProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.desabilitarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (tipoCadastro.equals("novo")){
            salvarProduto();
        } else if(tipoCadastro.equals("alteracao")){
            alterarProduto();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoBarrasKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cbFornecedores.grabFocus();
        }
    }//GEN-LAST:event_tfCodigoBarrasKeyReleased

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void listarFornecedor(){
        listaFornecedor = controllerFornecedor.getListaFornecedorController();
        cbFornecedores.removeAllItems();
        for (int i = 0; i < listaFornecedor.size(); i++){
            cbFornecedores.addItem(listaFornecedor.get(i).getNome());
        }
    }
    
   
    
    private boolean recuperarProduto() {
        //recebe a linha selecionada
        int linha = this.tbProdutos.getSelectedRow();
        //pega o codigo do cliente na linha selecionada
        int codigo = (Integer) tbProdutos.getValueAt(linha, 0);
        try {
            //recupera os dados do banco
            modelProdutos = controllerProdutos.getProdutosController(codigo);
            //seta os dados na interface
            this.tfCodigo.setText(String.valueOf(modelProdutos.getCodigo()));
            this.jtfNome.setText(modelProdutos.getNome());
            this.tfValor.setText(modelProdutos.getValor().toString());
            this.tfEstoque.setText(String.valueOf(modelProdutos.getEstoque()));
            this.cbFornecedores.setSelectedItem(controllerFornecedor.getFornecedorController(modelProdutos.getFornecedoresCodigo()).getNome());
            this.tfCodigoBarras.setText(String.valueOf(modelProdutos.getCodigoBarras()));
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    
    private boolean alterarProduto(){
        modelProdutos.setCodigo(Integer.parseInt(this.tfCodigo.getText()));
        modelProdutos.setNome(this.jtfNome.getText());
        modelProdutos.setValor(Double.parseDouble(this.tfValor.getText()));
        modelProdutos.setFornecedoresCodigo(controllerFornecedor.getFornecedorController(this.cbFornecedores.getSelectedItem().toString()).getCodigo());
        modelProdutos.setEstoque(Integer.parseInt(this.tfEstoque.getText()));
        modelProdutos.setCodigoBarras(this.tfCodigoBarras.getText());
        //salvar 
        if (controllerProdutos.atualizarProdutosController(modelProdutos)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            this.desabilitarCampos();
            this.carregarProdutos();
            limparDados();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
     private void carregarProdutos() {
        listamModelProdutos = controllerProdutos.getListaProdutosController();
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listamModelProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listamModelProdutos.get(i).getCodigo(),
                listamModelProdutos.get(i).getNome(),
                listamModelProdutos.get(i).getValor(),
                listamModelProdutos.get(i).getEstoque()
            });
        }
    }
     
     private void limparDados(){
        jtfNome.setText("");
        tfValor.setText("");
        tfEstoque.setText("");
//        tfPesquisaProduto.setText("");
        tfCodigoBarras.setText("");
     }
    
    protected void desabilitarCampos(){
        tfCodigoBarras.setEditable(false);
        jtfNome.setEditable(false);
        tfValor.setEditable(false);
        tfEstoque.setEditable(false);
        cbFornecedores.setEnabled(false);
        btCancelar.setEnabled(false);
        btAlterar.setEnabled(false);
        btSalvar.setEnabled(false);
        
//        tfPesquisaProduto.setEditable(false);
        carregarProdutos();
    }
    
    private void novoProduto(){
        habilitarCampos();
        tfCodigo.setText("Novo");
        jtfNome.setText("");
        tfValor.setText("");
        tfEstoque.setText("");
        tfCodigoBarras.setText("");
        cbFornecedores.setSelectedItem("");
        tipoCadastro = "novo";
    }
    
    private void habilitarCampos(){
        jtfNome.setEditable(true);
        tfValor.setEditable(true);
        tfEstoque.setEditable(true);
        cbFornecedores.setEnabled(true);
        btSalvar.setEnabled(true);
        tfCodigoBarras.setEditable(true);
        btCancelar.setEnabled(true);
        btAlterar.setEnabled(true);
        
    }
    
    private boolean salvarProduto(){
        
        modelProdutos.setNome(this.jtfNome.getText());
        modelProdutos.setValor(Double.parseDouble(this.tfValor.getText()));
        modelProdutos.setFornecedoresCodigo(controllerFornecedor.getFornecedorController(this.cbFornecedores.getSelectedItem().toString()).getCodigo());
        modelProdutos.setEstoque(Integer.parseInt(this.tfEstoque.getText()));
        modelProdutos.setCodigoBarras(this.tfCodigoBarras.getText());
        //salvar 
        if (controllerProdutos.salvarProdutosController(modelProdutos)>0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
            this.desabilitarCampos();
            this.carregarProdutos();
            limparDados();
            habilitarCampos();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private componentes.UJComboBox cbFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigoBarras;
    private javax.swing.JFormattedTextField tfEstoque;
    private javax.swing.JFormattedTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
