/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.map.clubedowhisky.view;

import br.edu.map.clubedowhisky.controller.ControllerCliente;
import br.edu.map.clubedowhisky.controller.ControllerFornecedor;
import br.edu.map.clubedowhisky.controller.ControllerProdutos;
import br.edu.map.clubedowhisky.controller.ControllerVendas;
import javax.swing.JFrame;
import br.edu.map.clubedowhisky.util.SessaoUsuario;
import br.edu.map.clubedowhisky.util.Datas;

/**
 *
 * @author IMPRESSAO
 */
public class TelaPrincipal extends javax.swing.JFrame {
 String pNomeUsuario;
 
    public TelaPrincipal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
         configurar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paninelIncones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Clientes = new javax.swing.JButton();
        btn_Produtos = new javax.swing.JButton();
        btn_Vendas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bnt_Fornecedor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_Usuarios = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        submenuClientes = new javax.swing.JMenuItem();
        submenuProdutos = new javax.swing.JMenuItem();
        submenuUsuarios = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        SubMenu_RelatorioCliente = new javax.swing.JMenuItem();
        SubMenu_Fornecedores = new javax.swing.JMenuItem();
        SubMenu_Produtos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        subMenuPesquisa_Clientes = new javax.swing.JMenuItem();
        subMenuPesquisa_Produtos = new javax.swing.JMenuItem();
        subMenuPesquisa_Usuarios = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        submenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clube do Whisky V1.0");
        setResizable(false);
        getContentPane().setLayout(null);

        paninelIncones.setBackground(new java.awt.Color(255, 153, 51));
        paninelIncones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paninelIncones.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial MT", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");
        paninelIncones.add(jLabel1);
        jLabel1.setBounds(20, 90, 50, 16);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial MT", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Produtos");
        paninelIncones.add(jLabel3);
        jLabel3.setBounds(110, 90, 60, 16);

        btn_Clientes.setBackground(java.awt.Color.white);
        btn_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/InconeClientes.png"))); // NOI18N
        btn_Clientes.setToolTipText("Clientes");
        btn_Clientes.setAutoscrolls(true);
        btn_Clientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Clientes.setBorderPainted(false);
        btn_Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientesActionPerformed(evt);
            }
        });
        paninelIncones.add(btn_Clientes);
        btn_Clientes.setBounds(10, 10, 80, 78);

        btn_Produtos.setBackground(java.awt.Color.white);
        btn_Produtos.setForeground(new java.awt.Color(255, 255, 255));
        btn_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/InconeProdutos.png"))); // NOI18N
        btn_Produtos.setToolTipText("Produtos");
        btn_Produtos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProdutosActionPerformed(evt);
            }
        });
        paninelIncones.add(btn_Produtos);
        btn_Produtos.setBounds(100, 10, 80, 78);

        btn_Vendas.setBackground(java.awt.Color.white);
        btn_Vendas.setForeground(new java.awt.Color(255, 255, 255));
        btn_Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/InconeVendas.png"))); // NOI18N
        btn_Vendas.setToolTipText("Vendas");
        btn_Vendas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VendasActionPerformed(evt);
            }
        });
        paninelIncones.add(btn_Vendas);
        btn_Vendas.setBounds(460, 10, 80, 78);

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial MT", 0, 12)); // NOI18N
        jLabel2.setText("Vendas");
        paninelIncones.add(jLabel2);
        jLabel2.setBounds(480, 90, 42, 16);

        btn_Pesquisar.setBackground(java.awt.Color.white);
        btn_Pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Incone_PesquisarUsuario.png"))); // NOI18N
        btn_Pesquisar.setToolTipText("Pesquisar");
        btn_Pesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });
        paninelIncones.add(btn_Pesquisar);
        btn_Pesquisar.setBounds(190, 10, 80, 78);

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial MT", 0, 12)); // NOI18N
        jLabel6.setText("Pesquisar");
        paninelIncones.add(jLabel6);
        jLabel6.setBounds(200, 90, 57, 16);

        bnt_Fornecedor.setBackground(java.awt.Color.white);
        bnt_Fornecedor.setForeground(new java.awt.Color(255, 255, 255));
        bnt_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone Fornecedor 48x48.png"))); // NOI18N
        bnt_Fornecedor.setToolTipText("Fornecedor");
        bnt_Fornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bnt_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_FornecedorActionPerformed(evt);
            }
        });
        paninelIncones.add(bnt_Fornecedor);
        bnt_Fornecedor.setBounds(370, 10, 80, 78);

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial MT", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fornecedor");
        paninelIncones.add(jLabel7);
        jLabel7.setBounds(380, 90, 63, 16);

        btn_Usuarios.setBackground(java.awt.Color.white);
        btn_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        btn_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone_Usuario48.png"))); // NOI18N
        btn_Usuarios.setToolTipText("Usuarios");
        btn_Usuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UsuariosActionPerformed(evt);
            }
        });
        paninelIncones.add(btn_Usuarios);
        btn_Usuarios.setBounds(280, 10, 80, 78);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial MT", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Usuários");
        paninelIncones.add(jLabel4);
        jLabel4.setBounds(300, 90, 51, 16);

        getContentPane().add(paninelIncones);
        paninelIncones.setBounds(0, 0, 730, 110);

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel.setText("Logado como:");

        jlUsuario.setText("usuario");

        jlData.setText("data");

        jLabel10.setText("Data/Hora de login:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlData))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 110, 730, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo sistema_2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 250, 160, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PlanodeFundo_2.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 110, 730, 390);

        menuCadastros.setText("Cadastros");
        menuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosActionPerformed(evt);
            }
        });

        submenuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        submenuClientes.setText("Clientes");
        submenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(submenuClientes);

        submenuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        submenuProdutos.setText("Produtos");
        submenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuProdutosActionPerformed(evt);
            }
        });
        menuCadastros.add(submenuProdutos);

        submenuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        submenuUsuarios.setText("Usuários");
        submenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuUsuariosActionPerformed(evt);
            }
        });
        menuCadastros.add(submenuUsuarios);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Fornecedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCadastros.add(jMenuItem1);

        barraMenuPrincipal.add(menuCadastros);

        menuRelatorios.setText("Relatorios");
        menuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosActionPerformed(evt);
            }
        });

        SubMenu_RelatorioCliente.setText("Clientes");
        SubMenu_RelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu_RelatorioClienteActionPerformed(evt);
            }
        });
        menuRelatorios.add(SubMenu_RelatorioCliente);

        SubMenu_Fornecedores.setText("Fornecedores");
        SubMenu_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu_FornecedoresActionPerformed(evt);
            }
        });
        menuRelatorios.add(SubMenu_Fornecedores);

        SubMenu_Produtos.setText("Produtos");
        SubMenu_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu_ProdutosActionPerformed(evt);
            }
        });
        menuRelatorios.add(SubMenu_Produtos);

        barraMenuPrincipal.add(menuRelatorios);

        jMenu1.setText("Pesquisar");

        subMenuPesquisa_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuPesquisa_Clientes.setText("Clientes");
        subMenuPesquisa_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuPesquisa_ClientesActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuPesquisa_Clientes);

        subMenuPesquisa_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuPesquisa_Produtos.setText("Produtos");
        subMenuPesquisa_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuPesquisa_ProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuPesquisa_Produtos);

        subMenuPesquisa_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuPesquisa_Usuarios.setText("Usuários");
        jMenu1.add(subMenuPesquisa_Usuarios);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Fornecedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        barraMenuPrincipal.add(jMenu1);

        menuSair.setText("Sair");

        submenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        submenuSair.setText("Sair");
        submenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuSairActionPerformed(evt);
            }
        });
        menuSair.add(submenuSair);

        barraMenuPrincipal.add(menuSair);

        setJMenuBar(barraMenuPrincipal);

        setSize(new java.awt.Dimension(744, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuClientesActionPerformed
        TelaCadastroCliente telaCliente =new TelaCadastroCliente();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_submenuClientesActionPerformed

    private void submenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuProdutosActionPerformed
        TelaCadastroProduto telaProdutos = new TelaCadastroProduto();
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_submenuProdutosActionPerformed

    private void menuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosActionPerformed

    }//GEN-LAST:event_menuCadastrosActionPerformed

    private void submenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_submenuSairActionPerformed

    private void submenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuUsuariosActionPerformed
       TelaCadastroUsuario telaUsuarios = new TelaCadastroUsuario();
       telaUsuarios.setVisible(true);
    }//GEN-LAST:event_submenuUsuariosActionPerformed

    private void subMenuPesquisa_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuPesquisa_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuPesquisa_ProdutosActionPerformed

    private void btn_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UsuariosActionPerformed

        TelaCadastroUsuario telaUsuarios = new TelaCadastroUsuario();
        telaUsuarios.setVisible(true);
    }//GEN-LAST:event_btn_UsuariosActionPerformed

    private void btn_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VendasActionPerformed
        TelaVenda tela =new TelaVenda();
        tela.setVisible(true);
    }//GEN-LAST:event_btn_VendasActionPerformed

    private void btn_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProdutosActionPerformed
        TelaCadastroProduto telaProdutos = new TelaCadastroProduto();
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_btn_ProdutosActionPerformed

    private void btn_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientesActionPerformed
        TelaCadastroCliente telaCliente =new TelaCadastroCliente();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btn_ClientesActionPerformed

    private void subMenuPesquisa_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuPesquisa_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuPesquisa_ClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCadastroFornecedor telaFornecedor =new TelaCadastroFornecedor();
        telaFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaPesquisarVendas telaPesquisarVendas =new TelaPesquisarVendas();
        telaPesquisarVendas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void bnt_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_FornecedorActionPerformed
      TelaCadastroFornecedor telaFornecedor =new TelaCadastroFornecedor();
      telaFornecedor.setVisible(true);
    }//GEN-LAST:event_bnt_FornecedorActionPerformed
 public String retornarUsuarioLogado(){
        return new SessaoUsuario().nome;
    }
    
    private void configurar(){
        pNomeUsuario = retornarUsuarioLogado();
        jlUsuario.setText(pNomeUsuario);
        Datas cwDatas = new Datas();
        jlData.setText(cwDatas.retornarDataHora());
        
    }
    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
      TelaPesquisarPrincipal telaPesquisarPrincipal =new  TelaPesquisarPrincipal();
      telaPesquisarPrincipal.setVisible(true);
    
      
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void menuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelatoriosActionPerformed

    private void SubMenu_RelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu_RelatorioClienteActionPerformed
        ControllerCliente controllerCliente = new ControllerCliente();
        controllerCliente.gerarRelatorioCliente();
                                                 
    }//GEN-LAST:event_SubMenu_RelatorioClienteActionPerformed

    private void SubMenu_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu_FornecedoresActionPerformed
        ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
        controllerFornecedor.gerarRelatorioFornecedor();
    }//GEN-LAST:event_SubMenu_FornecedoresActionPerformed

    private void SubMenu_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu_ProdutosActionPerformed
        // imprimir produtos
        ControllerProdutos controllerProdutos = new ControllerProdutos();
        controllerProdutos.gerarRelatorioProdutos();
    }//GEN-LAST:event_SubMenu_ProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SubMenu_Fornecedores;
    private javax.swing.JMenuItem SubMenu_Produtos;
    private javax.swing.JMenuItem SubMenu_RelatorioCliente;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JButton bnt_Fornecedor;
    private javax.swing.JButton btn_Clientes;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Produtos;
    private javax.swing.JButton btn_Usuarios;
    private javax.swing.JButton btn_Vendas;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JPanel paninelIncones;
    private javax.swing.JMenuItem subMenuPesquisa_Clientes;
    private javax.swing.JMenuItem subMenuPesquisa_Produtos;
    private javax.swing.JMenuItem subMenuPesquisa_Usuarios;
    private javax.swing.JMenuItem submenuClientes;
    private javax.swing.JMenuItem submenuProdutos;
    private javax.swing.JMenuItem submenuSair;
    private javax.swing.JMenuItem submenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
